version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - ENV_FILE=.env
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: secure_ai_assistant
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: